import type { ToolType, ToolDefinition } from '@/types/tools'

export const TOOL_DEFINITIONS: Record<ToolType, ToolDefinition> = {
  outline: {
    icon: '📝',
    cardTitle: '细纲生成器',
    description: '根据故事设定生成详细的章节细纲',
    title: '细纲生成器',
    hasNovelSelector: true, // 标记需要小说选择器
    fields: [
      {
        key: 'selectedNovel',
        label: '选择小说',
        type: 'novel-select',
        placeholder: '请选择要生成细纲的小说',
        required: true,
      },
      {
        key: 'selectedChapters',
        label: '参考章节',
        type: 'chapter-select',
        placeholder: '选择要参考的章节（可多选）',
      },
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'outline',
      },
      {
        key: 'chapters',
        label: '章节数量',
        type: 'input',
        placeholder: '预计章节数（建议5-15章）',
      },
    ],
  },
  cheat: {
    icon: '✨',
    cardTitle: '金手指生成器',
    description: '为主角设计独特的特殊能力',
    title: '金手指生成器',
    hasNovelSelector: true, // 标记需要小说选择器
    fields: [
      {
        key: 'selectedNovel',
        label: '选择小说',
        type: 'novel-select',
        placeholder: '请选择要生成金手指的小说',
        required: true,
      },
      {
        key: 'selectedChapters',
        label: '参考章节',
        type: 'chapter-select',
        placeholder: '选择要参考的章节（可多选）',
      },
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'cheat',
      },
      {
        key: 'level',
        label: '能力等级',
        type: 'select',
        placeholder: '选择等级',
        required: true,
        options: [
          { label: '初级', value: 'low' },
          { label: '中级', value: 'medium' },
          { label: '高级', value: 'high' },
          { label: '神级', value: 'god' },
        ],
      },
      {
        key: 'description',
        label: '特殊要求',
        type: 'textarea',
        placeholder: '描述特殊要求或偏好（可选）',
      },
    ],
  },
  opening: {
    icon: '🚀',
    cardTitle: '黄金开篇生成器',
    description: '创造引人入胜的小说开头',
    title: '黄金开篇生成器',
    fields: [
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'opening',
      },
      {
        key: 'genre',
        label: '小说类型',
        type: 'select',
        placeholder: '选择类型',
        required: true,
        options: [
          { label: '都市', value: 'urban' },
          { label: '玄幻', value: 'fantasy' },
          { label: '悬疑', value: 'mystery' },
          { label: '言情', value: 'romance' },
        ],
      },
      {
        key: 'mood',
        label: '开篇氛围',
        type: 'select',
        placeholder: '选择氛围',
        required: true,
        options: [
          { label: '紧张刺激', value: 'tense' },
          { label: '温馨平和', value: 'warm' },
          { label: '神秘悬疑', value: 'mysterious' },
          { label: '幽默轻松', value: 'humorous' },
        ],
      },
      {
        key: 'protagonist',
        label: '主角设定',
        type: 'textarea',
        placeholder: '简要描述主角特点',
        required: true,
      },
      { key: 'scene', label: '开篇场景', type: 'input', placeholder: '开篇场景或环境' },
    ],
  },
  title: {
    icon: '💎',
    cardTitle: '爆款书名生成器',
    description: '生成吸引读者的书名',
    title: '爆款书名生成器',
    fields: [
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'title',
      },
      {
        key: 'count',
        label: '生成数量',
        type: 'select',
        placeholder: '选择生成数量',
        required: true,
        options: [
          { label: '5个书名', value: '5' },
          { label: '10个书名', value: '10' },
          { label: '15个书名', value: '15' },
          { label: '20个书名', value: '20' },
        ],
      },
      {
        key: 'genre',
        label: '小说类型',
        type: 'select',
        placeholder: '选择类型',
        required: true,
        options: [
          { label: '都市', value: 'urban' },
          { label: '玄幻', value: 'fantasy' },
          { label: '科幻', value: 'scifi' },
          { label: '言情', value: 'romance' },
          { label: '悬疑', value: 'mystery' },
        ],
      },
      {
        key: 'keywords',
        label: '关键词',
        type: 'input',
        placeholder: '输入相关关键词，用逗号分隔',
        required: true,
      },
      {
        key: 'style',
        label: '风格偏好',
        type: 'select',
        placeholder: '选择风格',
        options: [
          { label: '霸气', value: 'domineering' },
          { label: '文艺', value: 'literary' },
          { label: '悬疑', value: 'mysterious' },
          { label: '简洁', value: 'simple' },
        ],
      },
    ],
  },
  genre: {
    icon: '🎯',
    cardTitle: '爆款题材生成器',
    description: '挖掘热门题材和创意点子',
    title: '爆款题材生成器',
    fields: [
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'inspiration',
      },
      {
        key: 'count',
        label: '生成数量',
        type: 'select',
        placeholder: '选择生成数量',
        required: true,
        options: [
          { label: '3个题材', value: '3' },
          { label: '5个题材', value: '5' },
          { label: '8个题材', value: '8' },
          { label: '10个题材', value: '10' },
        ],
      },
      {
        key: 'trend',
        label: '流行趋势',
        type: 'select',
        placeholder: '选择趋势',
        required: true,
        options: [
          { label: '当前热门', value: 'current' },
          { label: '经典永恒', value: 'classic' },
          { label: '新兴题材', value: 'emerging' },
        ],
      },
      {
        key: 'target',
        label: '目标读者',
        type: 'select',
        placeholder: '选择读者群体',
        required: true,
        options: [
          { label: '年轻人', value: 'young' },
          { label: '中年人', value: 'middle' },
          { label: '全年龄', value: 'all' },
        ],
      },
      {
        key: 'elements',
        label: '元素偏好',
        type: 'textarea',
        placeholder: '希望包含的元素或避免的元素',
      },
    ],
  },
  brainstorm: {
    icon: '🧠',
    cardTitle: '脑洞生成器',
    description: '激发创意灵感的随机想法',
    title: '脑洞生成器',
    fields: [
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'brainstorm',
      },
      {
        key: 'count',
        label: '生成数量',
        type: 'select',
        placeholder: '选择生成数量',
        required: true,
        options: [
          { label: '3个脑洞', value: '3' },
          { label: '5个脑洞', value: '5' },
          { label: '8个脑洞', value: '8' },
          { label: '10个脑洞', value: '10' },
        ],
      },
      {
        key: 'type',
        label: '脑洞类型',
        type: 'select',
        placeholder: '选择类型',
        required: true,
        options: [
          { label: '世界设定', value: 'world' },
          { label: '角色设定', value: 'character' },
          { label: '情节转折', value: 'plot' },
          { label: '能力设定', value: 'ability' },
        ],
      },
      {
        key: 'creativity',
        label: '创意程度',
        type: 'select',
        placeholder: '选择程度',
        required: true,
        options: [
          { label: '常规', value: 'normal' },
          { label: '新颖', value: 'novel' },
          { label: '天马行空', value: 'wild' },
        ],
      },
      { key: 'base', label: '基础设定', type: 'textarea', placeholder: '现有的设定基础（可选）' },
    ],
  },
  synopsis: {
    icon: '📋',
    cardTitle: '简介生成器',
    description: '生成精彩的小说简介和推荐语',
    title: '简介生成器',
    hasNovelSelector: true, // 标记需要小说选择器
    fields: [
      {
        key: 'selectedNovel',
        label: '选择小说',
        type: 'novel-select',
        placeholder: '请选择要生成简介的小说',
        required: true,
      },
      {
        key: 'selectedChapters',
        label: '参考章节',
        type: 'chapter-select',
        placeholder: '选择要参考的章节（可多选）',
      },
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'synopsis',
      },
      {
        key: 'style',
        label: '简介风格',
        type: 'select',
        placeholder: '选择风格',
        options: [
          { label: '悬疑吸引', value: 'suspense' },
          { label: '直白介绍', value: 'direct' },
          { label: '情感共鸣', value: 'emotional' },
        ],
      },
    ],
  },
  worldview: {
    icon: '🌍',
    cardTitle: '宏大世界观生成器',
    description: '构建完整的虚构世界背景',
    title: '宏大世界观生成器',
    hasNovelSelector: true, // 标记需要小说选择器
    fields: [
      {
        key: 'selectedNovel',
        label: '选择小说',
        type: 'novel-select',
        placeholder: '请选择要生成世界观的小说',
        required: true,
      },
      {
        key: 'selectedChapters',
        label: '参考章节',
        type: 'chapter-select',
        placeholder: '选择要参考的章节（可多选）',
      },
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'worldview',
      },
      {
        key: 'type',
        label: '世界类型',
        type: 'select',
        placeholder: '选择类型',
        required: true,
        options: [
          { label: '奇幻世界', value: 'fantasy' },
          { label: '科幻未来', value: 'scifi' },
          { label: '古代历史', value: 'ancient' },
          { label: '现代都市', value: 'modern' },
        ],
      },
      {
        key: 'scale',
        label: '世界规模',
        type: 'select',
        placeholder: '选择规模',
        required: true,
        options: [
          { label: '单一城市', value: 'city' },
          { label: '国家大陆', value: 'continent' },
          { label: '多个星球', value: 'planets' },
          { label: '宇宙级别', value: 'universe' },
        ],
      },
    ],
  },
  character: {
    icon: '👤',
    cardTitle: '角色生成器',
    description: '创建丰富立体的人物角色',
    title: '角色生成器',
    fields: [
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'character',
      },
      {
        key: 'count',
        label: '生成数量',
        type: 'input',
        placeholder: '输入数量（1-15个角色）',
        required: true,
      },
      {
        key: 'role',
        label: '角色定位',
        type: 'select',
        placeholder: '选择定位',
        required: true,
        options: [
          { label: '主角', value: 'protagonist' },
          { label: '配角', value: 'supporting' },
          { label: '反派', value: 'antagonist' },
          { label: '路人', value: 'background' },
        ],
      },
      {
        key: 'gender',
        label: '性别',
        type: 'select',
        placeholder: '选择性别',
        options: [
          { label: '男性', value: 'male' },
          { label: '女性', value: 'female' },
          { label: '不限', value: 'any' },
        ],
      },
      {
        key: 'personality',
        label: '性格特点',
        type: 'textarea',
        placeholder: '期望的性格特点',
        required: true,
      },
    ],
  },
  conflict: {
    icon: '⚡',
    cardTitle: '冲突生成器',
    description: '设计引人入胜的故事冲突',
    title: '冲突生成器',
    hasNovelSelector: true, // 标记需要小说选择器
    fields: [
      {
        key: 'selectedNovel',
        label: '选择小说',
        type: 'novel-select',
        placeholder: '请选择要生成冲突的小说',
        required: true,
      },
      {
        key: 'selectedChapters',
        label: '参考章节',
        type: 'chapter-select',
        placeholder: '选择要参考的章节（可多选）',
      },
      {
        key: 'selectedPrompt',
        label: '提示词模板',
        type: 'prompt-select',
        placeholder: '选择提示词模板（可选）',
        category: 'conflict',
      },
      {
        key: 'type',
        label: '冲突类型',
        type: 'select',
        placeholder: '选择类型',
        required: true,
        options: [
          { label: '人物冲突', value: 'character' },
          { label: '社会冲突', value: 'social' },
          { label: '内心冲突', value: 'internal' },
          { label: '环境冲突', value: 'environment' },
        ],
      },
      {
        key: 'intensity',
        label: '冲突强度',
        type: 'select',
        placeholder: '选择强度',
        required: true,
        options: [
          { label: '轻微', value: 'mild' },
          { label: '中等', value: 'moderate' },
          { label: '激烈', value: 'intense' },
        ],
      },
      { key: 'background', label: '背景设定', type: 'textarea', placeholder: '故事背景和现有冲突' },
    ],
  },
}

/** Tool output contracts apply equally to default prompts and user templates. */
export const TOOL_OUTPUT_REQUIREMENTS: Record<ToolType, string> = {
  outline: '只生成指定数量的章节细纲，不生成章节正文或全书策划案。每章包含标题、主要情节、冲突与转折、人物关系变化；章节之间保持连续性，与参考角色和世界观一致。',
  cheat: '生成一个符合所选能力等级的金手指设定，包含能力名称与效果、获取和触发条件、限制与代价、成长路径，以及与小说世界和情节的结合点。',
  opening: '只输出小说开篇正文，长度控制在500-800字。采用所选类型和氛围，体现主角特点与开篇场景，立即引入冲突或悬念；不输出大纲或创作说明。',
  title: '生成指定数量的书名，每项附简短创意说明。符合小说类型、关键词和风格偏好，书名以3-8个字为佳，避免重复和俗套。',
  genre: '提供指定数量的题材方向，符合流行趋势、目标读者和元素偏好。每项包含名称、核心概念、潜力、创作要点与创新方向。',
  brainstorm: '提供指定数量的脑洞，符合所选脑洞类型和创意程度，围绕基础设定展开。每项包含标题、核心设定、创意亮点和发展方向。',
  synopsis: '只输出100-200字的小说简介，不写章节正文、章节大纲或整部故事。遵循简介风格，突出主角、核心冲突、故事亮点和悬念，与已有设定一致。',
  worldview: '构建符合所选世界类型和规模的完整世界观，不生成故事正文。覆盖地理、社会制度、文化、科技或力量体系、历史和规则，与参考小说和角色一致。',
  character: '生成指定数量的角色档案，所有角色遵循所选定位、性别和性格要求。每项包括姓名、外貌、性格、背景、能力与弱点、动机、人际关系和情节作用；多个角色必须有差异。',
  conflict: '设计符合所选冲突类型和强度的冲突情节，结合背景与小说已有设定。包含起因、各方动机、升级过程、转折高潮、解决方向及对人物的影响。',
}
